using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//https://kan-kikuchi.hatenablog.com/entry/Mathf

public class SimpleMove : MonoBehaviour
{
    //private Vector3 v3Position = new Vector3(0.0f, 0.5f, 0.0f);
    //private Vector3 v3Velocity = new Vector3(0.2f, 0.0f, 0.0f);
    //private Vector3 v3Velocity = new Vector3(0.1f, 0.0f, 0.0f);
    //private float fVelocity = 0.1f;
    //private float fAngle = Mathf.PI / 6.0f;

    //private Vector3 v3BasePosition = new Vector3(0.0f, 6.0f, 0.0f);
    //private Vector3 v3BaseVelocity = new Vector3(0.1f, 0.0f, 0.0f);
    //private Vector3 v3BasePosition = new Vector3(-5.0f, 0.5f, 0.0f);
    private Vector3 v3BasePosition = new Vector3(0.0f, 0.5f, 0.0f);
    private Vector3 v3BaseVelocity = new Vector3(0.1f, 0.2f, 0.0f);
    //private Vector3 v3Position;
    //private Vector3 v3Velocity;
    private float fGravity = -0.003f;
    private float t = 0.0f;//æ™‚åˆ»


    private const float fRot_r = 5.0f;//å›è»¢åŠå¾„
    private const float fAngle_Vel = 2.0f * Mathf.PI / 50.0f;
    private Vector3 v3Position = new Vector3(fRot_r, 0.5f, 0.0f);//ä½ç½®
    private Vector3 v3Velocity = new Vector3(0.0f, 0.0f, fRot_r * fAngle_Vel);
    private float fAngle = 0.0f;//è§’åº¦

    void Start()
    {
        //StartSimpleMove1_1or2();
        //StartSimpleMove1_1a();
        //StartSimpleMove2_1();
        //StartSimpleMove3_1();
        //StartSimpleMove3_2();
        //StartSimpleMove4_1();
        //StartSimpleMove4_2();
        //StartSimpleMove4_3();
        //StartSimpleMove5_1();
        //StartSimpleMove5_1a();
        //StartSimpleMove5_2();
        //StartSimpleMove6_1();
        StartSimpleMove6_2();
    }

    void Update()
    {

    }

    private void FixedUpdate()
    {
        //FixedUpdateSimpleMove1_1();
        //FixedUpdateSimpleMove1_2();
        //FixedUpdateSimpleMove1_1a();
        //FixedUpdateSimpleMove2_1();
        //FixedUpdateSimpleMove2_2();
        //FixedUpdateSimpleMove2_3();
        //FixedUpdateSimpleMove3_1();
        //FixedUpdateSimpleMove3_2();
        //FixedUpdateSimpleMove4_1();
        //FixedUpdateSimpleMove4_2();
        //FixedUpdateSimpleMove4_3();
        //FixedUpdateSimpleMove5_1();
        //FixedUpdateSimpleMove6_1();
        FixedUpdateSimpleMove6_2();
    }

    //void StartSimpleMove1_1or2()
    //{
    //    transform.position = v3Position;
    //}

    //void FixedUpdateSimpleMove1_1()
    //{
    //    v3Position = v3Position + v3Velocity;

    //    transform.position = v3Position;
    //}

    //void FixedUpdateSimpleMove1_2()
    //{
    //    v3Position = v3Position + v3Velocity;

    //    if (5.0f < v3Position.x)
    //    {
    //        v3Position.x = 5.0f;
    //        v3Velocity.x = -v3Velocity.x;
    //    }
    //    if (v3Position.x < -5.0f)
    //    {
    //        v3Position.x = -5.0f;
    //        v3Velocity.x = -v3Velocity.x;
    //    }

    //    transform.position = v3Position;
    //}

    //void StartSimpleMove1_1a()
    //{
    //    transform.position = new Vector3(0.0f, 0.5f, 0.0f);
    //}

    //void FixedUpdateSimpleMove1_1a()
    //{
    //    transform.Translate(0.2f, 0.0f, 0.0f);
    //}

    //void StartSimpleMove2_1()
    //{
    //    transform.position = v3Position;
    //}

    //void FixedUpdateSimpleMove2_1()
    //{
    //    Vector3 v3Velocity = new Vector3(0.0f, 0.0f, 0.0f);
    //    v3Velocity.x = Input.GetAxis("Horizontal") * fVelocity;

    //    v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½

    //    transform.position = v3Position;

    //    if (transform.position.x > 5.0f)
    //    {
    //        transform.position = new Vector3(5.0f, transform.position.y, transform.position.z);
    //    }
    //    if (transform.position.x < -5.0f)
    //    {
    //        transform.position = new Vector3(-5.0f, transform.position.y, transform.position.z);
    //    }
    //}

    //void FixedUpdateSimpleMove2_2()
    //{
    //    Vector3 v3Velocity = new Vector3(0.0f, 0.0f, 0.0f);
    //    v3Velocity.x = Input.GetAxis("Horizontal") * fVelocity;
    //    v3Velocity.z = Input.GetAxis("Vertical") * fVelocity;

    //    v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½

    //    if (v3Position.x > 5.0f)
    //    {
    //        v3Position.x = 5.0f;
    //    }
    //    if (v3Position.x < -5.0f)
    //    {
    //        v3Position.x = -5.0f;
    //    }
    //    if (v3Position.z > 5.0f)
    //    {
    //        v3Position.z = 5.0f;
    //    }
    //    if (v3Position.z < -5.0f)
    //    {
    //        v3Position.z = -5.0f;
    //    }

    //    transform.position = v3Position;
    //}

    //void FixedUpdateSimpleMove2_3()
    //{
    //    Vector3 v3Velocity = new Vector3(0.0f, 0.0f, 0.0f);
    //    v3Velocity.x = Input.GetAxis("Horizontal") * fVelocity;
    //    v3Velocity.z = Input.GetAxis("Vertical") * fVelocity;

    //    float fInputVel = Mathf.Sqrt(v3Velocity.x * v3Velocity.x + v3Velocity.z * v3Velocity.z);//ï¿½ï¿½ï¿½ï¿½

    //    if (fInputVel > fVelocity)
    //    {
    //        v3Velocity = v3Velocity / fInputVel * fVelocity;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //    }

    //    v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½

    //    if (v3Position.x > 5.0f)
    //    {
    //        v3Position.x = 5.0f;
    //    }
    //    if (v3Position.x < -5.0f)
    //    {
    //        v3Position.x = -5.0f;
    //    }
    //    if (v3Position.z > 5.0f)
    //    {
    //        v3Position.z = 5.0f;
    //    }
    //    if (v3Position.z < -5.0f)
    //    {
    //        v3Position.z = -5.0f;
    //    }

    //    transform.position = v3Position;
    //}

    //void StartSimpleMove3_1()
    //{
    //    transform.position = v3Position;
    //    v3Velocity.x = fVelocity * Mathf.Cos(fAngle);//ï¿½ï¿½ï¿½ï¿½ï¿½Ìİ’ï¿½
    //    v3Velocity.y = fVelocity * Mathf.Sin(fAngle);
    //}

    //void FixedUpdateSimpleMove3_1()
    //{
    //    v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½

    //    if ((v3Position.x > 5.0f) || (v3Position.x < -5.0f) || (v3Position.z > 5.0f) || (v3Position.z < -5.0f))//ï¿½nï¿½Ê‚ï¿½ï¿½ï¿½oï¿½Ä‚ï¿½ï¿½é‚©
    //    {
    //        v3Position = new Vector3(0.0f, 0.5f, 0.0f);//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //    }

    //    transform.position = v3Position;
    //}

    //void StartSimpleMove3_2()
    //{
    //    transform.position = v3Position;
    //}

    //void FixedUpdateSimpleMove3_2()
    //{
    //    v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½

    //    if ((v3Position.x > 5.0f) || (v3Position.x < -5.0f) || (v3Position.z > 5.0f) || (v3Position.z < -5.0f))//ï¿½nï¿½Ê‚ï¿½ï¿½ï¿½oï¿½Ä‚ï¿½ï¿½é‚©
    //    {
    //        v3Position = new Vector3(0.0f, 0.5f, 0.0f);//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //        fAngle += 2.0f * Mathf.PI / 10.0f;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½]
    //        if (fAngle > (2.0f * Mathf.PI))//Mathf.PIï¿½Íƒï¿½ //ï¿½ï¿½ï¿½ï¿½ifï¿½Æ’ï¿½ï¿½gï¿½ÍAï¿½pï¿½xï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½å‚«ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½pï¿½xï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
    //        {
    //            fAngle -= 2.0f * Mathf.PI;
    //        }
    //        v3Velocity.x = fVelocity * Mathf.Cos(fAngle);
    //        v3Velocity.z = fVelocity * Mathf.Sin(fAngle);
    //    }

    //    transform.position = v3Position;
    //}

    void StartSimpleMove4_1()
    {
        v3Position = v3BasePosition;//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        v3Velocity = v3BaseVelocity;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove4_1()
    {
        v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½
        v3Velocity.y += fGravity;//ï¿½ï¿½ï¿½xï¿½É‰ï¿½ï¿½ï¿½ï¿½xï¿½ğ‘«‚ï¿½

        if (v3Position.y < 0.0f)//ï¿½nï¿½Ê‚É—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            v3Position = v3BasePosition;//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            v3Velocity = v3BaseVelocity;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }

        transform.position = v3Position;
    }

    void StartSimpleMove4_2()
    {
        v3Position = v3BasePosition;//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        v3Velocity = v3BaseVelocity;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove4_2()
    {
        v3Position += v3Velocity;//ï¿½Ê’uï¿½É‘ï¿½ï¿½xï¿½ğ‘«‚ï¿½
        v3Velocity.y += fGravity;//ï¿½ï¿½ï¿½xï¿½É‰ï¿½ï¿½ï¿½ï¿½xï¿½ğ‘«‚ï¿½

        if (v3Position.y < 0.0f)//ï¿½nï¿½Ê‚É—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            v3Position = v3BasePosition;//ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            v3Velocity = v3BaseVelocity;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }

        transform.position = v3Position;
    }

    void StartSimpleMove4_3()
    {
        v3Position = v3BasePosition;//ä½ç½®ã‚’åˆæœŸåŒ–
        t = 0.0f;//æ™‚åˆ»ã‚’åˆæœŸåŒ–
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove4_3()
    {
        v3Position.x = v3BaseVelocity.x * t + v3BasePosition.x;//ä½ç½®ã«åŠ é€Ÿåº¦ã‚’è¶³ã™
        v3Position.y = 0.5f * fGravity * t * t + v3BaseVelocity.y * t + v3BasePosition.y;//é€Ÿåº¦ã«åŠ é€Ÿåº¦ã‚’è¶³ã™
        t++;

        if (v3Position.y < 0.0f)//åœ°é¢ã«è½ã¡ãŸã‹
        {
            t = 0.0f;//æ™‚åˆ»ã‚’åˆæœŸåŒ–
        }

        transform.position = v3Position;
    }

    void StartSimpleMove5_1()
    {
        v3Position = v3BasePosition;//ä½ç½®ã‚’åˆæœŸåŒ–
        v3Velocity = new Vector3(Random.Range(-0.2f, 0.2f), 0.2f, Random.Range(-0.2f, 0.2f));//é€Ÿåº¦ã‚’åˆæœŸåŒ–
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove5_1()
    {
        v3Position += v3Velocity;//ä½ç½®ã«é€Ÿåº¦ã‚’è¶³ã™
        v3Velocity.y += fGravity;//é€Ÿåº¦ã«åŠ é€Ÿåº¦ã‚’è¶³ã™

        if (v3Position.y < 0.0f)
        {
            Destroy(gameObject);//åœ°é¢ã«è½ã¡ãŸã‹
        }

        transform.position = v3Position;
    }

    void StartSimpleMove5_1a()
    {
        float fRadius, fAngle;
        v3Position = v3BasePosition;//ä½ç½®ã‚’åˆæœŸåŒ–
        fRadius = Random.Range(0.0f, 0.2f);
        fAngle = Random.Range(0.0f, 2.0f * Mathf.PI);
        v3Velocity = new Vector3(fRadius * Mathf.Cos(fAngle), 0.2f, fRadius * Mathf.Sin(fAngle));//é€Ÿåº¦ã‚’åˆæœŸåŒ–
        transform.position = v3Position;
    }

    void StartSimpleMove5_2()
    {
        float fRand_r, fRand_Angle;
        v3Position = v3BasePosition;//ä½ç½®ã‚’åˆæœŸåŒ–
        fRand_r = Mathf.Sqrt(-2.0f * Mathf.Log(Random.Range(0.0f, 1.0f)));// âˆš-2ln(a)
        fRand_Angle = Random.Range(0.0f, 2.0f * Mathf.PI);
        v3Velocity = new Vector3(0.2f * fRand_r * Mathf.Cos(fRand_Angle), 0.2f, 0.2f * fRand_r * Mathf.Sin(fRand_Angle));//é€Ÿåº¦ã‚’åˆæœŸåŒ–
        transform.position = v3Position;
    }

    void StartSimpleMove6_1()
    {
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove6_1()
    {
        v3Position = new Vector3(fRot_r * Mathf.Cos(fAngle), 0.5f, fRot_r * Mathf.Sin(fAngle));//å›è»¢
        fAngle += 2.0f * Mathf.PI / 50.0f;//è§’åº¦ã‚’é€²ã‚ã‚‹
        transform.position = v3Position;
    }

    void StartSimpleMove6_2()
    {
        transform.position = v3Position;
    }

    void FixedUpdateSimpleMove6_2()
    {
        v3Position += v3Velocity;//ä½ç½®ã«é€Ÿåº¦ã‚’
        v3Velocity += -new Vector3(v3Position.x, 0.0f, v3Position.z) * fAngle_Vel * fAngle_Vel;//é€Ÿåº¦ã«åŠ é€Ÿåº¦ã‚’
        transform.position = v3Position;
    }
}
